version: 2.1

environment: &base-env
    NPM_CONFIG_PROGRESS: 'false'
    NPM_CONFIG_LOGLEVEL: warn
    
executors:
  node-container:
    docker:
      - image: node:12
        environment: *base-env

  node-container-next-lts:
    docker:
      - image: node:14
        environment: *base-env

jobs:
  dependency-check:
    executor: node-container
    steps:
      - checkout
      - run:
          name: Create Dependency Check sandbox
          command: mkdir -p ./dependency-check
      - run:
          name: Create Package JSON
          command: node ./scripts/dependency-check/create-manifest-from-template
      - run:
          name: Check Outdated
          working_directory: ./dependency-check
          command: (npm outdated --json || true) > ./outdated.json
      - run:
          name: Create new template
          command: node ./scripts/dependency-check/create-template-from-outdated
      - run:
          name: Run Tests and Produce Reports
          command: |
            FORMER_CWD="$(pwd)"
            PROJECT=test-$(date +%s)
            mkdir "${TMPDIR}/${PROJECT}"
            cd "${TMPDIR}/${PROJECT}"
            npx @contentful/create-contentful-app init test
            cd test
            (CI=true npm t || true) 1>"${FORMER_CWD}/dependency-check/test-report" 2>&1
      - run:
          name: Create Pull Request
          command: npm install @octokit/rest@18 simple-git@2 && node ./scripts/dependency-check/create-pull-request
      - run:
          name: Cleanup
          command: rm -rf ./dependency-check

  lint-and-test: &lint-and-test
    executor: node-container
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run Tests
          command: npm t

  lint-and-test-next-lts:
    <<: *lint-and-test
    executor: node-container-next-lts

  test-built-app: &test-built-app
    executor: node-container
    steps:
      - checkout
      - run:
          name: Run Tests
          environment:
            MODE: 'ci'
          command: |
            PROJECT=test-$(date +%s)
            mkdir "${TMPDIR}/${PROJECT}"
            cd "${TMPDIR}/${PROJECT}"
            npx @contentful/create-contentful-app init test
            cd test
            npm t
  
  test-built-app-next-lts:
    <<: *test-built-app
    executor: node-container-next-lts

workflows:
  version: 2

  scheduled-dependency-check:
    triggers:
      - schedule:
          # Run each day at midnight
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - dependency-check

  test:
    jobs:
      - lint-and-test
      - lint-and-test-next-lts
      - test-built-app:
          requires:
            - lint-and-test
            - lint-and-test-next-lts
      - test-built-app-next-lts:
          requires:
            - lint-and-test
            - lint-and-test-next-lts
