# https://dependabot.com/docs/config-file/#dependabot-config-files
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "build"
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    ignored_updates:
      - match:
          dependency_name: "husky"
          version_requirement: ">=5.0.0"

